### ISSUE TITLE
Handshake failure with PM2 cluster mode

### ISSUE THREAD

**Issue by tectual** [socketio/socket.io-redis#142]
Hi,

Is this supposed to solve the handshake problem with multiple instances? 

Sometimes it is connected at first try and some other times it just keep trying and it may establish connection after few tries...

```
VM5983:35 WebSocket connection to 'ws://localhost:3000/socket.io/?EIO=3&transport=websocket&sid=Fpn-vkHqf6k6fypKAAAE' failed: Connection closed before receiving a handshake response
```

Thanks.

**Comment by darrachequesne** [comment]
No, this module only allow broadcasting between nodes.

**Comment by tectual** [comment]
@darrachequesne   Can you guide me on this? So far no luck in solving it and really don't want to use sticky session solution.

I need to have cluster + socket.io, but hand shakes fails.

**Comment by jreeter** [comment]
You have to have sticky sessions, so handshake requests get routed to the same socket process. If not, then the handshake will fail.

**Comment by darrachequesne** [comment]
@tectual there has been some work in that direction (https://github.com/socketio/engine.io/pull/416), but it's a work in progress.

The thing is that the handshake is not the only step that might fails in a multi-node configuration. The messages waiting to be sent to the client must also be shared, since the client can reach any node in polling mode. And the data received from the client must be redirected to the server "owning" the client, where the callbacks are registered.

**Comment by tectual** [comment]
@jreeter I thought sticky sessions are not generally good (Or let's say not the best way to load balance). I hoped I can avoid using it. But seems thats the only option left out.

Thanks @jreeter and @darrachequesne.
