### ISSUE TITLE
How to get the socket object given a socket id 

### ISSUE THREAD

**Issue by sbsomya** [socketio/socket.io-redis#200]
Hi 
I have a requirement we are using multiple node servers and socket connections using socket.io-redis
Getting the socket id for the people connected inside the room but how to get the socket object

**Comment by artofspeed** [comment]
no way to do that natively, try https://github.com/socketio/socket.io-redis#redisadaptercustomrequestdataobject-fnfunction

**Comment by sbsomya** [comment]
Yes this might help me out somehow 
Just in customHook getting cb is undefined

**Comment by darrachequesne** [comment]
Could you please try with version 4.0.0? (https://github.com/socketio/socket.io-redis/pull/181 was not included in earlier version)

**Comment by lakamsani** [comment]
Hi, just tried 4.0.0. callback is getting called. However the semantics seems to be a bit different what we commonly use in node. When the callback from custom app code in io.sockets.adapter.customHook,  only the first argument is being passed back to customRequest.

To elaborate lets say I call the callback in these 3 different ways in io.sockets.adapter.customHook

1. callback("success")
2. callback (null, "success")
3. callback(new Error("bad bad"))

Then with  the io.sockets.adapter.customRequest callback signature like this:
````javascript
io.sockets.adapter.customRequest(arg, function(err, replies){
  if (err) {
    console.log("error")
 } else {
   console.log(replies)
 }  
})
````
It never hits the error cases although 3 and may be 1 to do it in a traditional node callback semantics. error is no null on system issues like timeouts (say put a breakpoint in customHook). Here is what is seen  in the  debugger for replies array with one element in else condition for each of the 3 cases above. 

1. "success" 
2. "null" 
3. some empty/undefined object. 

A couple of semi-related questions. 

- is it possible to tune this timeout of the response form customHook to customRequest.
- some of our direct HMSETs to redis or lua scripts from [redlock](https://github.com/mike-marcacci/node-redlock)  are returning error code of MOVED from redis. But this problem is not seen with socket.io-redis. Are you guys handling this internally (any pointers to that code would be great). I heard ioredis handles these MOVED requests in the cluster transparently. Is socketio-redis supported with ioredis? If so what version.
- customRequest/customHook  seems to be very much dependent on node_redis 2.6.3. Tried with 2.6.5 with either 3.1.0 or 4.0.0 of socket.io-redis and custmHook was never getting called. 

Thanks.

**Comment by lakamsani** [comment]
the above test seems to work/behave similarly with ioredis 3.0.0.

**Comment by arden** [comment]
@artofspeed 
How to get the socket object given a socket id
i think this is very useful for point-to-point chat.

**Comment by lakamsani** [comment]
@arden  getting a socket given a socket id is pretty straight forward on a given server. use something like this:
````javascript
var ns = global.io.of(namespace || "/"); 
 var socket = ns.connected[id] // assuming you have  id of the socket
````
The discussion in this thread and the other is focussed around looking/getting hold of socket object in a cluster  using a socket attribute (say like email) when the socket is not present on the local server i.e. When searching on the socket attributes in the sockets in ns.connected does not find a match. 
https://github.com/socketio/socket.io-redis/issues/137
I don't think the socket ids are server specific and you need some other common attribute like email to find sockets on remote servers for a common group.

**Comment by knoxcard** [comment]
When a new socket connection comes in, store the socket id into an array.  I attached a UUID per session as well.

```
// set uuid session
const uuid = require('uuid')
app.use(function(req, res, next) {
  if(typeof(req.session.uuid) === 'undefined') {
    req.session.uuid = uuid()
  }
})

var socket_clients = {}
var ios = require('socket.io')(server)
ios.sockets.on('connection', function(socket) {
  console.log('[new socket connection]')
  socket_clients[socket.request.session.uuid] = socket.id
  setTimeout(function() {
    ios.sockets.to(socket_clients[socket.request.session.uuid]).emit('paymentComplete', {'bitcoin_address': 'x289sHjwjweAYWUIENXJ233opp4'})
  }, 4000)
  ios.sockets.on('disconnect', function(socket_disconnect) {
    console.log('[socket disconnected]')
  })
})
ios.use(function(socket, next) {
  session(socket.request, socket.request.res, next)
})


```

**Comment by cowboybkit** [comment]
@sbsomya `if (sockets.io.nsps['/'].adapter.rooms[roomName]) `  has error: sockets is not defined
Please define "sockets" variable?

**Comment by apoorvans** [comment]
I have a similar problem for the above referenced 1 on 1 chat use case. I need to emit to a particular socket (given its id) and do some processing in the callback. The socket itself may of course be on another node. I tried: `io.to(socketId).emit(event, data);`
This works. I imagine it is essentially notifying the connected node to the given socketId and asking it to emit data. 

But when I add a callback: `io.to(socketId).emit(event, data, callback);` , it throws this:
`Callbacks are not supported when broadcasting`

Curious about the correct approach. I am on latest 5.1.0.

**Comment by efkan** [comment]
I need to get socket objects.

I send some data as `header` (handshake data) from clients to the server. In some cases I need get this header data again.
To accomplish that the socket objects must be gotten by using socket id via `socket.io-redis`.

**Comment by darrachequesne** [comment]
Please use the customHook / customRequest [methods](https://github.com/socketio/socket.io-redis#redisadaptercustomrequestdataobject-fnfunction).

I'm closing this for now, please open another issue if needed.
