### ISSUE TITLE
Unhandled error event

### ISSUE THREAD

**Issue by mathiask88** [socketio/socket.io-redis#21]
Hey,
I implemented a redis adapter in this way

``` javascript
var socketioPub = m_redis.createClient(null, null, { detect_buffers: true });
socketioPub.on('error', function (err) { ... });
var socketioSub = m_redis.createClient(null, null, { detect_buffers: true });
socketioSub.on('error', function (err) { ... });
io.adapter(m_socketio_redis({ pubClient: socketioPub, subClient: socketioSub }));
```

So if the redis server e.g. is not running I can handle that error, but I get an unhandled error event from https://github.com/Automattic/socket.io-redis/blob/master/index.js#L73

``` javascript
[...]
  function Redis(nsp){
    Adapter.call(this, nsp);

    var self = this;
    sub.psubscribe(prefix + '#*', function(err){
      if (err) self.emit('error', err); <--------------------------------
    });
    sub.on('pmessage', this.onmessage.bind(this));
  }
[...]
```

because there is no event listener attached and I see no way to attach one from the outside. Any ideas?

Best regards!

**Comment by dalerobbins** [comment]
None of the solutions mentioned in the posts here work at all with socket.io-redis 0.1.4. Socket.io's docs have always lacked proper documentation, especially for people coming to node for the first time. I have seen so many stackexchange posts describing the same common problems with socket.io that one would think those problems would have been fixed after people still mentioning them after more than a few years. This isn't exaggerated. I've pulled so much hair in the past trying to get something to work with socket.io, trying other peoples posts and the one thing that kills me is that most of the posts don't even mention the version of the software they are even talking about when describing a solution to a problem. I do have socket.io working but as a test I have shutdown a redis server that is being connected to by a node js app in order to test error code. Yes I have a listener on "error" for my redis client which works like it should. The problem is socket.io-redis. There doesn't seem to be anything to attach a listener on, node bitches about undefined when trying all the solutions currently mentioned here. And no I don't feel like browsing over someone else's code either, I have my own to deal with.

The problem here is not being able to provide an error listener for socket.io-redis so my app doesn't crash when it doesn't need to.

**Comment by pkuhonker** [comment]
@nkzawa 3x! You are right. Using radis adapter API also need to add of(namespace)!!!

**Comment by raulferras** [comment]
`io.of('/').adapter.on('error', funtion(err) {});` this didn't work for me, 
only adding the handler to the prototype as @peteruithoven suggesed worked for me

**Comment by edevil** [comment]
Same. Using version `5.2.0` and only catching errors on the pubClient and subClient still caused my app to crash.
```
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
```

Adding:
```
  adapter.prototype.on("error", err => logger.error("PROTOTYPE", { err }));
```

will prevent the app from crashing:
```
2018-10-25T10:17:56.307Z error: PROTOTYPE [err: Error: connect ECONNREFUSED 127.0.0.1:6379] [severity: ERROR]
2018-10-25T10:17:56.308Z error: PROTOTYPE [err: Error: connect ECONNREFUSED 127.0.0.1:6379] [severity: ERROR]
2018-10-25T10:17:56.467Z error: PROTOTYPE [err: MaxRetriesPerRequestError: Reached the max retries per request limit (which is 3). Refer to "maxRetriesPerRequest" option for details.] [severity: ERROR]
```

However, it will not retry forever to establish the Redis connection and will stay zombie.

**Comment by salmanahmad94** [comment]
> Same. Using version `5.2.0` and only catching errors on the pubClient and subClient still caused my app to crash.
> 
> ```
> Error: connect ECONNREFUSED 127.0.0.1:6379
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
> ```
> 
> Adding:
> 
> ```
>   adapter.prototype.on("error", err => logger.error("PROTOTYPE", { err }));
> ```
> 
> will prevent the app from crashing:
> 
> ```
> 2018-10-25T10:17:56.307Z error: PROTOTYPE [err: Error: connect ECONNREFUSED 127.0.0.1:6379] [severity: ERROR]
> 2018-10-25T10:17:56.308Z error: PROTOTYPE [err: Error: connect ECONNREFUSED 127.0.0.1:6379] [severity: ERROR]
> 2018-10-25T10:17:56.467Z error: PROTOTYPE [err: MaxRetriesPerRequestError: Reached the max retries per request limit (which is 3). Refer to "maxRetriesPerRequest" option for details.] [severity: ERROR]
> ```
> 
> However, it will not retry forever to establish the Redis connection and will stay zombie.

To keep the reconnection protocol, instantiate the redis client separately from the adapter. Implement reconnection protocols on this redis client and let it reconnect. Let adapter.prototype.on catch the error handle even redundantly.  That way, you'll get the best of both worlds.
