### ISSUE TITLE
Error - Could not parse

### ISSUE THREAD

**Issue by swapnil001** [socketio/socket.io-redis#278]
I am using socket.io-redis - 5.2.0
redis - 2.8.0

When I start the app following error is coming - 

Error: Could not parse
1|app      |     at Decoder.parse (/node_modules/notepack.io/lib/decode.js:239:9)
at Redis.onmessage (/node_modules/socket.io-redis/index.js:148:24)

**Comment by swapnil001** [comment]
The message is coming as Buffer and notepack.io is not able to decode it. Any solution for this?

**Comment by stiang** [comment]
Spent many hours tracing this problem. I don’t think it being a Buffer is relevant - at least it wasn’t in my case.

In my case, it turned out that I had other server processes on old versions of socket.io-redis and/or socket.io-emitter sending what seems like malformed MessagePack data. Here’s a test script I used to debug this:

```js
const notepack = require('notepack.io');

// A real (failing) message that I intercepted and converted to base 64
const b64str = 'k6ZIRHpyYkSDpHR5cGUCpGRhdGGSp3ZlcnNpb26mMC4xNi4zo25zcKEvgqVyb29tc8SlZmxhZ3PE';
const buf = Buffer.from(b64str, 'base64');
console.log('buf', buf);
console.log('str', buf.toString('utf8'));
// It crashes on the next line
const decoded = notepack.decode(buf);
console.log('decoded', decoded);
```

The base64 string is what came from the old processes. In the UTF-8 version you’ll see that it contains some weird characters towards the end (right before "flags"):

```
                                            weird character
                                                   |
��HDzrbD��type^B�data��version�0.16.3�nsp�/��roomsĥflags�      <-- broken
��hxoDYp��type^B�data��version�0.16.3�nsp�/��rooms��flags�     <-- OK
````

If you debug `notepack.io/decode.js` you’ll see that it parses the message just fine until it reaches those bytes.

I actually tried decoding the same string with [msgpack-lite](https://github.com/kawanet/msgpack-lite) just to see if it was a notepack.io bug, but it failed in a similar manner, so I’m pretty sure the message is simply malformed.

I solved the problem by upgrading socket.io-redis and socket.io-emitter on all my server processes. Your mileage may vary.

**Comment by knoxcard** [comment]
@swapnil001 - close ticket?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
