### ISSUE TITLE
Struggling to make the chat sample with clusters

### ISSUE THREAD

**Issue by liviuignat** [socketio/socket.io-redis#31]
Hi,

I forked yesterday this repo: https://github.com/liviuignat/chat-example-cluster, where basically I am trying to make the chat sample application with cluster and socket.io-redis so I can post it on Heroku and have a valid, strong sample of socket.io spawned over multiple node processes. The heroku url where it is posted is this: http://chat-example-cluster.herokuapp.com/

There seems to be more questions than solutions, related to this topic, and no concrete example to make it work, this is why I decided to create this example.

Unfortunately I am having problems with the setup and I would appreciate some help, if you could take a look here (https://github.com/liviuignat/chat-example-cluster/blob/master/index.js).

Most of the times I get "Connection closed before receiving a handshake response" on localhost. On Heroku I get "failed: Error during WebSocket handshake: Unexpected response code: 503" and "et::ERR_INCOMPLETE_CHUNKED_ENCODING".

From what I see nothing is being stored on redis also.

Any help would really be appreciated.

Thanks,

**Comment by poppahorse** [comment]
@peteruithoven did you ever resolve your polling issues? getting something similar, even though using cluster and socket.io-redis

**Comment by peteruithoven** [comment]
I solved my issues by implementing sticky sessions in HAProxy. It's mentioned in the docs: http://socket.io/docs/using-multiple-nodes/#

**Comment by coommark** [comment]
Cool! This thread cleared a lot of things for me! @peteruithoven thanks for clearing up what socket.io-redis does and doesn't. But let me ask a few questions. Pls I need help!
1. I want to manage user connections by adding them to a room by that username. So that I can emit to that user (assuming he has multiple clients or browsers). Let me clarify further:
A. User X connects to instance A of socket.io, a room is created for him on that instance..
B. The same user X connects with a different browser to instance B of socket.io, a room is also created for him there.
C. User Y sends a message to user X, how do I send the message to each of the rooms of user X on either of the socket.io?

2. Why does socket.io-redis have the name "redis" in it? Does it mean it stores something in redis?
3. If Yes to question (2) above, then I have to worry about redis too right? You know make sure redis never goes down, cos if it does, the whole app will be in deep caca with a paddle, right?

**Comment by peteruithoven** [comment]
> 1. I want to manage user connections by adding them to a room by that username. So that I can emit to that user (assuming he has multiple clients or browsers). Let me clarify further:
> A. User X connects to instance A of socket.io, a room is created for him on that instance..
> B. The same user X connects with a different browser to instance B of socket.io, a room is also created for him there.
> C. User Y sends a message to user X, how do I send the message to each of the rooms of user X on either of the socket.io?

One solution would be to have clients use a url parameter when they connect that could identify them, a login of sorts. Then you can add add the clients to rooms with a unique id, like their username. When you then receive a message from user Y you can broadcast to the room with the user X's username.  Would that solve your problem? 

> Why does socket.io-redis have the name "redis" in it? Does it mean it stores something in redis?

I'm not completely sure whether nothing gets stored, but it mostly uses redis's pub/sub mechanism. 

> If Yes to question (2) above, then I have to worry about redis too right? You know make sure redis never goes down, cos if it does, the whole app will be in deep caca with a paddle, right?

True...

**Comment by squivo** [comment]
The missing ingredient is on the client side : 

var socketIO = io.connect( url , {transports : ['websockets']});
socketIO.emit(...)

I have a forked working version without sticky ( which is sooo super buggy ) here : https://github.com/squivo/chat-example-cluster

**Comment by annehaha** [comment]
According to https://github.com/evilstudios/chat-example-cluster, when I run 'node index.js' and open index.html with browser, I can't see it works. Is that wrong?

**Comment by mike-aungsan** [comment]
@squivo https://github.com/socketio/socket.io-redis/issues/192 ?

**Comment by mike-aungsan** [comment]
@peteruithoven 


Can you show me example? I do not see API in doc. 

Broadcasting to all clients in rooms / namespaces
Broadcast to a specific client (because a client is automatically added into a room with it's socket.id as name)

Many Thanks

**Comment by m-garin** [comment]
You can see my [socket.io chat example](https://github.com/m-garin/node.js-cluster-socket.io-rooms) that has cluster and rooms support.

**Comment by UzverNumber47** [comment]
Hello guys! I just wanted to summarize.
I have 2 node servers on separate machines and a nginx load balancer.
In order to make all those websockets to work I need to enable sticky sessions on my load balancer and install socket.io-redis or any other mechanism that will broadcast events from one server to other.

Without sticky sessions everything will work only in clustered environment on the same machine, right?
