### ISSUE TITLE
Getting ECONNRESET  error

### ISSUE THREAD

**Issue by niroshana1234** [socketio/socket.io-redis#342]
I am getting the below error every 5 min time. But still, the application socket connection is working. Can you tell how can I get rid of this error?

Error: Redis connection to 192.168.10.12:6379   failed - read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)

Below is the code

var server = require('http').Server(app);
var io = require('socket.io')(server);
var redis = require('socket.io-redis');
io.adapter(redis( {host: "192.168.10.12", port: 6379}));

**Comment by darrachequesne** [comment]
This error indicates that you somehow lost connection with the Redis server.

You can catch it with (reference: https://github.com/socketio/socket.io-redis#client-error-handling):

```js
io.of('/').adapter.on('error', (err) => {
  // ...
});
```

**Comment by gollobo** [comment]
Hello, I'm still experiencing the same issue. I've tried with various Redis hosts in case that was the problem. I've also tried using both redis-node and ioredis, but it doesn't seem to work either. I've tried with TLS and without TLS. I'm a bit desperate because the error randomly restarts my Node.js server a couple of times a day. I've tried the following solutions:

Catch the error with:
```
pubClient.on("error", function(err){ console.log(err)});
```

```
server.listen(process.env.PORT || 3000, () => {
 //logic here
}).on('error', function (err) {
    console.log(err);
});
```

```
process.on('uncaughtException', function (err) {
    console.log(err.stack)
});
```

```
io.of('/').adapter.on('error', function (error) {
  console.log('error: ', error);
});
```

None of these solutions catch the error. Obviously, if I remove Redis and the adapter, it stops happening. Thank you very much for your help.

My code to start the server:

```
const http = require("http");
const express = require('express')
const app = express()
app.use(express.json({ limit: '1mb' }))
const server = http.createServer(app);
const { Server } = require("socket.io");
const { createAdapter } = require('@socket.io/redis-adapter');
const Redis = require('ioredis');

const pubClient = new Redis("Redis_url_here");
const subClient = pubClient.duplicate();

pubClient.on("error", logError);

subClient.on("error", logError);

const io = new Server(server);

io.adapter(createAdapter(pubClient, subClient));
server.listen(process.env.PORT || 3000, () => {
  if (process.send) process.send('ready');
  console.log('listening on port');
}).on('error', function (err) {
    console.log(err);
});
```

With this code the server works well and all the cluster are correctly connected via redis, but randomly have the crash ´read ECONNRESET´ :(

ioredis version: 5.3.2
redis version: 4.6.10
adapter version: 8.2.1
