### ISSUE TITLE
Get => io.sockets.connected[id_socket]

### ISSUE THREAD

**Issue by NicolasCELLA** [socketio/socket.io-redis#357]
Hello, an idea how to have the properties of a socket by id ?
Like  "io.sockets.connected[id_socket]" without redis !

Objectif: 
```
io.in(room_id).clients((err, clients) => {
     clients.forEach(socket => {
          // Get socket with her properties 
    }
});
```

Thank for your time 👍

**Comment by darrachequesne** [comment]
You can use the `customHook/customRequest` methods:

```js
// on every node
io.of('/').adapter.customHook = (socketId, cb) => {
  const socket = io.sockets.connected[socketId];
  cb(socket ? socket.handshake : null);
}

// then
const socketId = 'abcd';
io.of('/').adapter.customRequest(socketId, function(err, replies){
  console.log(replies); // an array [null, <handshake>, null, ...] with one element per node
});
```

Given the number of questions around this, I think we should maybe update the `clients()` or create another method. For you use-case, which properties do you need? `handshake`?

**Comment by webdpro** [comment]
@darrachequesne  The custom hook is kind of confusing, I have tried to use it but I'm having a hard time with fully understanding how it works or should work and the docs seems very light on it with few example. 

For our purpose when a user connects we add into the 'socket' a nickname, so when connecting we add socket.nickname='nickname' so its always tied to the socket, however because that is not shared across each instance with redis we cant use it and have been trying to hack through it with custom redis lists etc. 

It would be amazing if there was a way to expose those with just the 'socket' so there was minimal re-coding. Maybe storing stringable objects from the socket in redis so it can be accessed across the nodes? 

I had posted a question about this a few days back because, as noted we are trying to keep a list of users online, in rooms etc so we store in a list things like {socket:socket,nickname:nickname} and push and pop that list, however with all the different events (connect, disconnect, reconnect) its proving not to be as reliable as we would like as things get missed at times and things just sit in the redis collection.

**Comment by darrachequesne** [comment]
Yes, exactly, the problem with storing data in Redis is the cleanup part.

You can remove values on `disconnect` event, but what if a server goes down? So now you also need to set a TTL, which is longer than the session duration, but not too long. Or you can frequently check and expand the expiry.

Basically, the `customHook/customRequest` method is a way to transmit data between servers. Calling `customRequest` sends a request over the Redis channel, and all the nodes respond with `customHook`. In that case, nothing is stored in Redis, it's only pubsub chat.

We could add a way to transfer the socket properties from one server to another, something like:

```js
const socket = await io.socket(id).fetch();
const nickname = socket.nickname;
```

Would an API like that fit your use case? Do you have any suggestion?

Note: in that case, we could also have:

```js
await io.socket(id).join("room1");
await io.socket(id).leave("room2");
await io.socket(id).disconnect();
```

**Comment by webdpro** [comment]
@darrachequesne, 

I think that would be a nice option to have as it seems to be a fairly common use-case.  In doing so would this actually be replicated the sockets on each node or would it be more of a placement holder of sorts? 

If its the later do you think it would cause performance issues? 

To you previous points about connects / disconnects.. yes this is a pain in the butt! We currently switch everything over to use hset / get and store just the socket and nickname in custom redis sets like 'onlineUsers-[uniq-name]' and add / remove users based on this however to your point, if the server gets disconnected or some other action happens when the server does not send the disconnect we are left with orphen sockets in the redis collection. 

I'm thinking of adding a function that basically does a cleanup say every 60 seconds maybe, something where we grab the total all sockets connected, take that list and then loop over all sockets in each room and try and delete them. Only problem with this is it could be expensive. 

This obviously is not a new issue, however your suggestion above if I'm understanding it correctly would mean we would not longer need to build our our redist sets to keep track of things outside socket.io-redis correct? Seems like that would be less error prone too.

**Comment by fliespl** [comment]
@darrachequesne @webdpro 

I am curious about this api approach.

Wouldn't it work the same as those customHooks?

We have it setup like that to get socket properties from other servers.

```
io.of('/').adapter.customRequest({
            option: 'get_user_info',
            socketId: socketIdid
        }, (err, results) => {
            if (err) {
            } else {
                // iterate results to find one that returned data
            }
        }
);


io.of('/').adapter.customHook = (data, cb) => {
    if (data.option === 'get_user_info') {
        let info = io.sockets.adapter.nsp.connected[data.socketId] ? io.sockets.adapter.nsp.connected[id].userInfo : null; // attached on socket.connect as socket.userInfo = 'xyz';
        cb(info);
    }
}
```

**Comment by darrachequesne** [comment]
@fliespl yes, it would indeed work the same as the `customHook` API.

The thing is: we have had reports of users that had issues with understanding how the `customRequest/customHook` API worked, hence the suggested change. Do you have any suggestion about this?

**Comment by fliespl** [comment]
@darrachequesne I guess providing some real-life examples should suffice - it's the piece that's missing in my opinion and is causing issues for people.

To implement by my first customHook / customRequest logic, I had to spend 0.5-1h to understand how it works by doing research in main code. I wasn't able to implement it by only based on documentation.

**Comment by darrachequesne** [comment]
For future readers: please check https://socket.io/docs/v4/server-instance/#Utility-methods
