### ISSUE TITLE
Suggestion/Question: Wouldn't be better to use ioredis instead of redis package?

### ISSUE THREAD

**Issue by damianof** [socketio/socket.io-redis#60]
ioredis seem to perform far better then redis
(https://github.com/luin/ioredis)

**Comment by msamblanet** [comment]
I am using ioredis with this package.   There was a small monkey-patch I had to do to ioredis to make it work.  ioredis returns buffers via pmessageBuffer instead of pmessage.  The snippet below is a hack I used on the sub instance to make work with socket.io-redis.  The return_buffers and detect_buffers flags are not needed.

While more direct support of ioredis (which is much more current and actively maintainted) would be nice, this seems to be sufficient for my applicaiton's needs.  

```js
// WARNING: Use of this will prevent message and pmessage handlers from being unregistered
// since our stub method will be registered instead...
var oldOn = redisClient.on;
redisClient.on = function(event, oldListener) {
    var self = this;
    switch (event) {
        case "pmessage":
            return oldOn("pmessageBuffer", function() {
                if (arguments.length > 1) arguments[1] = arguments[1].toString();
                return oldListener.apply(self, arguments);
            });

        case "message":
            return oldOn("messageBuffer", function() {
                if (arguments.length) arguments[0] = arguments[0].toString();
                return oldListener.apply(self, arguments);
            });

        default: return oldOn.apply(self, oldListener);
    }
}
```

**Comment by mindfireon812** [comment]
Any Update ?

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-redis/pull/95.
