### ISSUE TITLE
Incompatibility with socket.io-emitter

### ISSUE THREAD

**Issue by aPoCoMiLogin** [socketio/socket.io-redis#78]
Well `socket.io-redis` is broken at the moment. Without some workaround you cant even use it: https://github.com/socketio/socket.io-redis/issues/73#issuecomment-158613469 and there come another issue, which broke compatibility with emits from `socket.io-emitter`, because of change `psubscribe` for `subscribe`: https://github.com/socketio/socket.io-redis/commit/800ef742451a0e98ecd5bf9ba36d36bbbd32e603 so other `socket.io-emitter` libs wont work too. If that two packages are related, why there is no tests with that package ?

**Comment by aPoCoMiLogin** [comment]
The only way at the moment is to stick with `0.1.3` version, and in options provide just `host` and `port`, to let use `socket.io-redis` his own `redis` package (which is same as `socket.io-emitter`). Its the way i get it working for now..

**Comment by GameXG** [comment]
Yes, python implementation encountered no compatibility problems. 0.1.4-> 0.2.0 also modified ms format.

The day before yesterday to achieve a socket.io-python-emitter compatible modifying 0.2.0, awaiting merged into the trunk. https://github.com/GameXG/socket.io-python-emitter/commit/2ece80ac4cfbe5c64ffccf93175a68e0b66cdd58

Why not do a more curious over it? 0.2.0 channel name prefix plus mark, while receiving the old version of the channel name, and slowly transition it?

**Comment by aPoCoMiLogin** [comment]
It's compatible after that commit: https://github.com/socketio/socket.io-emitter/commit/e656600388bdb3fc1cf62331e18d1a6a7775ab36 tested it today, and it works. Though that they will not fix that, cause last commit was a year ago.. So the issue resolved at the moment.

**Comment by toblerpwn** [comment]
@aPoCoMiLogin - fwiw, this was fixed here: https://github.com/socketio/socket.io-emitter/pull/27 and released as `socket.io-emitter 0.3.0`. your issue is even more apropos since `socket.io-redis 0.2.0` was released to npm with this issue, though.

our company (like the unit tests) actually missed this original break in `socket.io-emitter` after `socket.io-redis` bumped to `0.2.0`, so we had a production outage (WHOOPS).

unsure the best way to ensure this doesn't happen in the future on "peer"-related modules/repos in general, but I'm sure @rauchg and @nkzawa would be curious if you have a suggestion. (unless they already have a "fix" for this type of failure.)

maybe all of these inter-related packages should run their unit tests on the _latest_ versions of each of their dependencies in `package.json` after any version in the `socket.io` family is bumped (at least majorly, if not minorly)...but that sounds really onerous?

in this one particular case, perhaps instead the construction of the `base#namespace#room` message pattern should be centralized in `socket.io-adapter` (if I understand the vision & module relationships properly?), or some other independent dependency. ultimately it feels like breaking code like this should never be copy/pasted/hard-coded in three (or more?) modules - it's very risky, and blew up in this case, AND makes synchronizing deployments somewhat more complex...so maybe the fix is not process/more unit tests, but a small architecture change?

**Comment by aPoCoMiLogin** [comment]
@toblerpwn huh thanks for the response, but I was faster by seconds :D anyway, there should be info in `readme` that it works with specific versions, and tests were make for specific version of `socket.io-redis` (talking about `socket.io-emitter`), then it will be more clear, cause I had to brake down both packages, check tests and compare `package.json` to find the issue. So the lists of compatible packages with their versions would be good enough, at least for me.

**Comment by rauchg** [comment]
@toblerpwn obviously the key is to always pin modules to versions and pay attention to version bumps. Perhaps we should have done `1.0.0` for `-redis` since it was breaking, and `1.0.0` for emitter. I'll do that now. I apologize for the disruption.

**Comment by rauchg** [comment]
Done 💥🎉
